version: '3.3'

volumes:
  postgres_data:
    driver: local
  mongo_data:

services:
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
  keycloak:
    image: jboss/keycloak:6.0.1
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
    ports:
      - 8480:8080
    depends_on:
      - postgres
  api:
    build: .
    command: nodemon --inspect ./bin/www
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - keycloak
  mongo:
    image: mongo:3.4
    container_name: mongo
    environment:
      MONGO_INITDB_DATABASE: dev-bookmarks
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - 27017:27017
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - mongo_data:/data/db
